### ISSUE TITLE
Deprecation warning in PHP 5.5

### ISSUE THREAD

**Issue by passiomatic** [graulund/tweetnest#80]
Hi there. After my hosting provider upgraded servers to PHP 5.5 I'm seeing a deprecated warning on my Tweetnest page:
```
Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in {domain.name}/tweets/inc/html.php on line 390
```

Is there a way to patch Tweetnest to make this warning to disappear?

**Comment by BrendonKoz** [comment]
I had the issue too. Update your file(s). The current version of the html.php file in the inc folder doesn't use the /e modifier.

**Comment by passiomatic** [comment]
@BrendonKoz: that did the trick! Thank you very much.
