### ISSUE TITLE
Can't reach archive

### ISSUE THREAD

**Issue by gummipunkt** [graulund/tweetnest#87]
Hey all,

i set up tweetnext and it works, but when i click on the right site for the archive:
The requested URL /2016/12 was not found on this server.

I renamed the .htaccess files, but it does't work.

**Comment by alexmuller** [comment]
Is there anything in your web server logs that would help with diagnosing the issue? Possibly a file inside `/var/log/apache2`?

**Comment by cmdrfletcher** [comment]
I have the same problem. When I click on an archive link in the right sidebar this happens:

https://playground.fletcher.de/fletcher/tweetnest/2017/06

Somehow /public_htm/ comes in the way.

```
fletcher@playground:~/public_html/tweetnest$ ll month.php
-rw-r--r-- 1 fletcher fletcher 1004 Jun 25 12:10 month.php
fletcher@playground:~/public_html/tweetnest$ pwd
/home/fletcher/public_html/tweetnest
```
