### ISSUE TITLE
Search string not parsing properly

### ISSUE THREAD

**Issue by geekafy** [graulund/tweetnest#89]
I just installed a fresh copy of TweetNest and noticed an issue with the search.

When I do a search, I get a 404. I looked at the generated URL and noticed that is parses as the following:

`https://twitter.myurl.com/search?q=apple`

It should be parsing as the following:

`https://twitter.myurl.com/search.php?q=apple`

When I add the `.php` after the search it works great!

Thanks!

**Comment by alexmuller** [comment]
It sounds like your `.htaccess` file might not be in place or working properly. It's got [a line which is supposed to ensure you don't need the `.php` extension](https://github.com/graulund/tweetnest/blob/60dc044fca8791b3c202a6aea0cb0e0ced2e8d17/.htaccess#L4). There are some steps in the installation instructions to do with `.htaccess` files.

**Comment by geekafy** [comment]
So true..... My error. It worked.

**Comment by alexmuller** [comment]
Glad you got it sorted! 👍
